name: mtq_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  marquee: ^2.2.3
  smooth_page_indicator: ^1.1.0
  fading_edge_scrollview: ^3.0.0
  circular_reveal_animation: ^2.0.1
  curved_navigation_bar: ^1.0.3
  flutter_map: ^6.0.1
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.0
  flutter_animate: ^4.2.0+1
  provider: ^6.0.5
  url_launcher: ^6.2.1
  url_launcher_android: ^6.2.0
  geolocator: ^10.1.0
  http: ^1.1.0
  dio: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/slider/
    - assets/images/icons/
    - assets/images/motif/
    - assets/images/logo/
    - assets/images/logo/kabupaten/
    - assets/images/card/
    - assets/images/pemondokan/
    - assets/images/arena/
    - assets/images/lokasi/
    - assets/images/profil/
