List<Map> listLokasiPemondokan = [
  {
    'kabupaten': 'Semua Kabupaten',
    'icon': 'logo.png',
    'putra': true,
    'putri': true,
    'pemilik': '',
    'alamat': '',
    'hp': '',
    'imgUrl': '',
    'lat': null,
    'long': null,
  },
  {
    'kabupaten': 'Tamiang',
    'icon': 'tamiang.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Heri Mahdani',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abbann',
    'hp': '085274651457',
    'imgUrl': '1.png',
    'lat': 2.456148,
    'long': 96.380469,
  },
  {
    'kabupaten': 'Banda Aceh',
    'icon': 'banda_aceh.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Losmen Andini',
    'alamat': 'Desa Air Dingin Jln. Tgk. Diujun',
    'hp': '08521234',
    'imgUrl': '1.png',
    'lat': 2.459135,
    'long': 96.377867,
  },
  {
    'kabupaten': 'Aceh Barat Daya',
    'icon': 'aceh_barat_daya.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Losmen Andini',
    'alamat': 'Desa Air Dingin Jln. Tgk. Diujun',
    'hp': '085274651457',
    'imgUrl': '1.png',
    'lat': 2.459122,
    'long': 96.377764,
  },
  {
    'kabupaten': 'Aceh Barat',
    'icon': 'aceh_barat.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Zulkarnain',
    'alamat': 'Desa Kuala Umo Jln. Tgk. Diujun',
    'hp': '08256666666',
    'imgUrl': '1.png',
    'lat': 2.558418,
    'long': 96.310665,
  },
];
