List<Map> listLokasiPemondokan = [
  {
    'kabupaten': 'Semua Kabupaten',
    'icon': 'logo.png',
    'putra': true,
    'putri': true,
    'pemilik': '',
    'alamat': '',
    'hp': '',
    'imgUrl': '',
    'lat': null,
    'long': null,
  },
  {
    'kabupaten': 'Aceh Jaya',
    'icon': 'aceh_jaya.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Mulyawan',
    'alamat': 'Desa Air Dingin Jln. Tgk Di Ujung',
    'hp': '085277474692',
    'imgUrl': '1.png',
    'lat': 2.45148,
    'long': 96.37671,
  },
  {
    'kabupaten': 'Aceh Jaya',
    'icon': 'aceh_jaya.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Ahmadi',
    'alamat': 'Desa Air Dingin Jln. Tgk Di Ujung',
    'hp': '081362868881',
    'imgUrl': '1.png',
    'lat': 2.45193,
    'long': 96.37685,
  },
  {
    'kabupaten': 'Aceh Barat',
    'icon': 'aceh_barat.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Syahrul Ali',
    'alamat': 'Desa Suak Buluh Jln. Tgk Di Ujung',
    'hp': '085260017879',
    'imgUrl': '1.png',
    'lat': 2.44447,
    'long': 96.37573,
  },
  {
    'kabupaten': 'Aceh Barat',
    'icon': 'aceh_barat.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Darmilis',
    'alamat': 'Desa Suak Buluh Jln. Tgk Di Ujung',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.44417,
    'long': 96.37523,
  },
  {
    'kabupaten': 'Aceh Besar',
    'icon': 'aceh_besar.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Asdarmansyah',
    'alamat': 'Desa Air Dingin Jln. Baru',
    'hp': '081360092092',
    'imgUrl': '1.png',
    'lat': 2.45724,
    'long': 96.37638,
  },
  {
    'kabupaten': 'Aceh Besar',
    'icon': 'aceh_besar.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Edi Arsyah, ST',
    'alamat': 'Desa Air Dingin Jln. Baru',
    'hp': '082249100063',
    'imgUrl': '1.png',
    'lat': 2.45894,
    'long': 96.37691,
  },
  {
    'kabupaten': 'Pidie',
    'icon': 'pidie.png',
    'putra': true,
    'putri': true,
    'pemilik': 'dr. Johny',
    'alamat': 'Desa Air Dingin Jln. Baru',
    'hp': '085270601945',
    'imgUrl': '1.png',
    'lat': 2.45942,
    'long': 96.37887,
  },
  {
    'kabupaten': 'Aceh Utara',
    'icon': 'aceh_utara.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Abi / Rofi',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '081264700374',
    'imgUrl': '1.png',
    'lat': 2.45423,
    'long': 96.38436,
  },
  {
    'kabupaten': 'Aceh Utara',
    'icon': 'aceh_utara.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Hermansyah, ST',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '082365257997',
    'imgUrl': '1.png',
    'lat': 2.4542,
    'long': 96.38448,
  },
  {
    'kabupaten': 'Bener Meriah',
    'icon': 'bener_meriah.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Safarian, ST.MT',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '082370838015',
    'imgUrl': '1.png',
    'lat': 2.45845,
    'long': 96.38963,
  },
  {
    'kabupaten': 'Bener Meriah',
    'icon': 'bener_meriah.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Marlin Tamaro',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '085276435325',
    'imgUrl': '1.png',
    'lat': 2.45825,
    'long': 96.38924,
  },
  {
    'kabupaten': 'Aceh Tenggara',
    'icon': 'aceh_tenggara.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Yahsanuddin',
    'alamat': 'Desa Air Dingin Jln. Baru Lrg Pinang',
    'hp': '082316312288',
    'imgUrl': '1.png',
    'lat': 2.45964,
    'long': 96.37505,
  },
  {
    'kabupaten': 'Aceh Tenggara',
    'icon': 'aceh_tenggara.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Edward Arosa',
    'alamat': 'Desa Air Dingin Jln. Baru Lrg Pinang',
    'hp': '08126009007',
    'imgUrl': '1.png',
    'lat': 2.45979,
    'long': 96.37531,
  },
  {
    'kabupaten': 'Aceh Tengah',
    'icon': 'aceh_tengah.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Sabu Nasir',
    'alamat': 'Desa Air Dingin Jln. Tgk Diujung',
    'hp': '085361336667',
    'imgUrl': '1.png',
    'lat': 2.46034,
    'long': 96.37932,
  },
  {
    'kabupaten': 'Langsa',
    'icon': 'langsa.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Putri Munawarah',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '085275289795',
    'imgUrl': '1.png',
    'lat': 2.45707,
    'long': 96.38088,
  },
  {
    'kabupaten': 'Langsa',
    'icon': 'langsa.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Zulfahri',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.45722,
    'long': 96.38113,
  },
  {
    'kabupaten': 'Aceh Selatan',
    'icon': 'aceh_selatan.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Murniati',
    'alamat': 'Desa Suka Jaya Jln. Baru',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.47874,
    'long': 96.3761,
  },
  {
    'kabupaten': 'Aceh Selatan',
    'icon': 'aceh_selatan.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Rahmad RSUD',
    'alamat': 'Desa Suka Jaya Jln. Baru',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.47887,
    'long': 96.37572,
  },
  {
    'kabupaten': 'Tamiang',
    'icon': 'tamiang.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Heru Madani',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '085274651457',
    'imgUrl': '1.png',
    'lat': 2.45613,
    'long': 96.38045
  },
  {
    'kabupaten': 'Aceh Barat Daya',
    'icon': 'aceh_barat_daya.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Losmen Andini',
    'alamat': 'Desa Air Dingin Jln. Tgk Diujung',
    'hp': '082277404198',
    'imgUrl': '1.png',
    'lat': 2.45914,
    'long': 96.37796
  },
  {
    'kabupaten': 'Banda Aceh',
    'icon': 'banda_aceh.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Losmen Andini',
    'alamat': 'Desa Air Dingin Jln. Tgk Diujung',
    'hp': '082277404198',
    'imgUrl': '1.png',
    'lat': 2.45916,
    'long': 96.37775
  },
  {
    'kabupaten': 'Simeulue',
    'icon': 'simeulue.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Mess Dokter',
    'alamat': 'Desa Ameria Bahagia Jln. Baru',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.46604,
    'long': 96.37829
  },
  {
    'kabupaten': 'Pidie Jaya',
    'icon': 'pidie_jaya.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Muhammad Daudsyah',
    'alamat': 'Desa Amaiteng Mulia Jln. Pahlawan',
    'hp': '081264321566',
    'imgUrl': '1.png',
    'lat': 2.48429,
    'long': 96.37444
  },
  {
    'kabupaten': 'Bireuen',
    'icon': 'bireuen.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Wardi Leo',
    'alamat': 'Desa Suka Karya Jln. Baru',
    'hp': '082370828874',
    'imgUrl': '1.png',
    'lat': 2.47149,
    'long': 96.3751
  },
  {
    'kabupaten': 'Bireuen',
    'icon': 'bireuen.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Buyung',
    'alamat': 'Desa Suka Karya Jln. Baru',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.47195,
    'long': 96.37576
  },
  {
    'kabupaten': 'Aceh Singkil',
    'icon': 'singkil.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Losmen Simeulue',
    'alamat': 'Desa Sinabang Jln. Sinabang',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.47816,
    'long': 96.38078
  },
  {
    'kabupaten': 'Lhokseumawe',
    'icon': 'lhokseumawe.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Rosmawati',
    'alamat': 'Desa Suak Buluh Jln. Tgk Diujung',
    'hp': '082188566070',
    'imgUrl': '1.png',
    'lat': 2.43426,
    'long': 96.37271
  },
  {
    'kabupaten': 'Lhokseumawe',
    'icon': 'lhokseumawe.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Murniati',
    'alamat': 'Desa Suak Buluh Jln. Tgk Diujung',
    'hp': '081365175787',
    'imgUrl': '1.png',
    'lat': 2.43437,
    'long': 96.37224
  },
  {
    'kabupaten': 'Aceh Timur',
    'icon': 'aceh_timur.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Nasfan',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '082276306161',
    'imgUrl': '1.png',
    'lat': 2.4541,
    'long': 96.38689
  },
  {
    'kabupaten': 'Aceh Timur',
    'icon': 'aceh_timur.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Ibu Neri',
    'alamat': 'Desa Air Dingin Jln. Ibnu Abban',
    'hp': '082233501601',
    'imgUrl': '1.png',
    'lat': 2.45394,
    'long': 96.3871
  },
  {
    'kabupaten': 'Subulussalam',
    'icon': 'subulussalam.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Parioto',
    'alamat': 'Desa Ameria Bahagia Lrg. Durian',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.46805,
    'long': 96.38018
  },
  {
    'kabupaten': 'Subulussalam',
    'icon': 'subulussalam.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Faradi',
    'alamat': 'Desa Ameria Bahagia Lrg. Durian',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.46803,
    'long': 96.38066
  },
  {
    'kabupaten': 'Gayo Lues',
    'icon': 'gayo_lues.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Isdayati Baroqah',
    'alamat': 'Desa Suka Karya Jln. Baru',
    'hp': '081260909080',
    'imgUrl': '1.png',
    'lat': 2.47952,
    'long': 96.37567
  },
  {
    'kabupaten': 'Gayo Lues',
    'icon': 'gayo_lues.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Erni',
    'alamat': 'Desa Suka Karya Jln. Baru',
    'hp': '-',
    'imgUrl': '1.png',
    'lat': 2.47858,
    'long': 96.3757
  },
  {
    'kabupaten': 'Nagan Raya',
    'icon': 'nagan_raya.png',
    'putra': true,
    'putri': false,
    'pemilik': 'Rislan',
    'alamat': 'Desa Air Dingin Lrg. Gajah Putih',
    'hp': '082276197173',
    'imgUrl': '1.png',
    'lat': 2.47692,
    'long': 96.37461
  },
  {
    'kabupaten': 'Nagan Raya',
    'icon': 'nagan_raya.png',
    'putra': false,
    'putri': true,
    'pemilik': 'Fenny Lestari',
    'alamat': 'Desa Air Dingin Lrg. Gajah Putih',
    'hp': '085360615659',
    'imgUrl': '1.png',
    'lat': 2.47673,
    'long': 96.37457
  },
  {
    'kabupaten': 'Sabang',
    'icon': 'sabang.png',
    'putra': true,
    'putri': true,
    'pemilik': 'Erlinda',
    'alamat': 'Desa Amaiteng Mulia Jln. Pahlawan',
    'hp': '085260906900',
    'imgUrl': '1.png',
    'lat': 2.48639,
    'long': 96.37024
  },
];
